[package]
name = "hk-crypto"
version.workspace = true
edition.workspace = true
[dependencies]
hk-proto = { path = "../hk-proto" }
ed25519-dalek.workspace = true
rand.workspace = true
blake3.workspace = true
bip39 = { version = "2", features = ["rand"] }
sharks = "0.5"
serde.workspace = true
borsh.workspace = true
p256 = { version = "0.13", features = ["ecdsa", "pkcs8"] }
x25519-dalek = { version = "2", features = ["static_secrets"] }
chacha20poly1305 = "0.10"
