use hk_net::{Message, Packet, Rollback};
use hk_proto::*;
use std::{
    collections::BTreeMap,
    time::{Duration, Instant, SystemTime, UNIX_EPOCH},
};
fn main() {
    if let Err(e) = run() {
        eprintln!("ERREUR: {e}");
        std::process::exit(1)
    }
}
fn run() -> Result<(), String> {
    let args: Vec<String> = std::env::args().collect();
    match args.get(1).map(|s|s.as_str()){
 Some("determinism")=>{println!("10 000 combats × 2 replays : {}",hex(&hk_sim::determinism_suite()));},
 Some("replay")=>{let path=args.get(2).ok_or("replay <preuve.json>")?;let text=std::fs::read_to_string(path).map_err(|e|e.to_string())?;let proof:serde_json::Value=serde_json::from_str(&text).map_err(|e|e.to_string())?;let start:Packet=serde_json::from_value(proof["start"].clone()).map_err(|e|e.to_string())?;if !start.valid(){return Err("Signature de départ invalide".into())}let Message::Start{cell,players,nonce}=start.message.clone()else{return Err("Départ manquant".into())};if players.first().map(|v|v.key)!=Some(start.author){return Err("Auteur de départ absent".into())}let mut rb=Rollback::new(cell,players.clone(),nonce,players[0].key)?;rb.seed_initial_delay();let packets:Vec<Packet>=serde_json::from_value(proof["inputs"].clone()).map_err(|e|e.to_string())?;let mut inputs=BTreeMap::new();for p in packets{if !p.valid(){return Err("Entrée non authentique".into())}let id=players.iter().position(|v|v.key==p.author).ok_or("Auteur étranger")?as u8;if let Message::Input{room,tick,input}=p.message{if room!=rb.room{return Err("Champ étranger".into())}if let Some(previous)=inputs.insert((tick,id),input){if previous!=input{return Err("Équivoque d'entrée".into())}}}}
 let tick=proof["tick"].as_u64().ok_or("Tick manquant")?as u32;for t in 3..=tick+3{for id in 0..players.len(){if let Some(input)=inputs.get(&(t,id as u8)){rb.inputs.insert((t,id as u8),*input);}else if t<=tick{return Err(format!("Entrée manquante au tick {t} / pair {id}"))}}}for t in 1..=tick{let values:Vec<_>=(0..players.len()).map(|id|(id as u8,rb.inputs.get(&(t,id as u8)).copied().unwrap_or_default())).collect();rb.battle.step(&values);}let hash=rb.battle.hash();if proof["hash"].as_str()!=Some(&hex(&hash)){return Err("Le hash final diverge".into())}let results:Vec<Packet>=serde_json::from_value(proof["results"].clone()).map_err(|e|e.to_string())?;let mut signatures=std::collections::BTreeSet::new();for p in results{if !p.valid(){return Err("Résultat non authentique".into())}if let Message::Finish{room,tick:t,hash:h}=p.message{if room==rb.room&&t==tick&&h==hash&&players.iter().any(|v|v.key==p.author){signatures.insert(p.author);}}}let complete=signatures.len()==players.len();println!("Rejeu identique : {}\nTick : {tick}\nSignatures : {}/{}\nFinalité Couronne : aucune",hex(&hash),signatures.len(),players.len());if !complete{return Err("Rejeu cohérent mais preuve incomplète, non validée".into())}},
 Some("peer")=>{let option=|name:&str|args.iter().position(|s|s==name).and_then(|i|args.get(i+1)).cloned();let id=option("--id").unwrap_or("1".into()).parse::<usize>().map_err(|e|e.to_string())?;let seconds=option("--seconds").unwrap_or("60".into()).parse::<u64>().map_err(|e|e.to_string())?;let autostart=option("--autostart").and_then(|s|s.parse::<usize>().ok());let mut g=hk_core::Game::new("",true);g.save.created=true;g.save.name=format!("PAIR-TEST-{id}");g.save.realm=Realm::from_index(id);g.save.role=Role::from_index(id);g.screen=7;g.start_network();if let Some(addr)=option("--connect"){g.connect(addr);}let start=Instant::now();let mut started=false;let mut last_check=0;let mut printed=0;while start.elapsed().as_secs()<seconds{let now=SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_secs();if let Some(b)=&g.battle{let id=g.online.as_ref().map(|o|o.rollback.local).unwrap_or(0);g.key_input=b.bot_input(id as usize);}g.tick(now);if g.addresses.len()>printed{for a in g.addresses.iter().skip(printed){println!("LISTEN {a}");}printed=g.addresses.len();}if let Some(n)=autostart{if !started&&g.peers.len()>=n{g.challenge(n>1);started=true;println!("CHAMP OUVERT {}",g.peers.len()+1);}}if let Some(o)=&g.online{let c=o.rollback.confirmed()/30*30;if c>last_check{if let Some(s)=o.rollback.states.get(&c){println!("CHECK {c} {}",hex(&s.hash()));}last_check=c;}if let Some(e)=&o.rollback.error{return Err(e.clone())}}if g.screen==12{g.finish_online();println!("COMBAT COSIGNÉ");break}std::thread::sleep(Duration::from_millis(33));}if g.online.is_some(){g.finish_online();}if let Some(path)=option("--out"){std::fs::write(path,g.last_proof).map_err(|e|e.to_string())?;}println!("PAIRS {}",g.peers.len());},
 _=>println!("HEXKEEP — simulateur de développement\n  determinism\n  replay <preuve.json>\n  peer --id 1 --seconds 180 [--connect /ip4/127.0.0.1/tcp/PORT] [--autostart 1] [--out preuve.json]\nLes pairs de test se découvrent sur le réseau local. Aucun Sceau n'est produit.")
}
    Ok(())
}
